---
- name: Postgres DB setup
  become: true
  become_user: postgres
  block:
  - name: Create database
    postgresql_db:
      name: "{{ dbname }}"
  - name: Create DB user
    postgresql_user:
      db: "{{ dbname }}"
      name: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      priv: "ALL"
      no_password_changes: "yes"
      role_attr_flags: "NOSUPERUSER,NOCREATEDB"
  - name: Ensure DB user password is correct
    command: "psql -c \"ALTER ROLE {{ dbuser }} WITH PASSWORD '{{ dbpassword }}';\""
  - name: Add postgis extension to DB
    postgresql_ext:
      db: "{{ dbname }}"
      name: "postgis"
    when: dbtype == 'postgis'
  when: dbname is defined
