---
- name: Django update sources and requirements
  tags: django
  vars:
    django_src_archive_path: /tmp/django-src.tar.gz
    requirements_archive_path: /tmp/requirements.tar.gz
  block:
    - name: Create Django project sources archive
      archive:
        path: "{{ django_src_path }}"
        dest: "{{ django_src_archive_path }}"
      delegate_to: localhost
    - name: Clean Django dir on remote server
      file:
        path: "{{ django_dir }}"
        state: absent
    - name: Create Django dir on remote server
      file:
        path: "{{ django_dir }}"
        state: directory
        mode: 0755
    - name: Copy Django project sources to the remote server
      unarchive:
        src: "{{ django_src_archive_path }}"
        dest: "{{ django_dir }}"
      notify:
        - restart uwsgi
    - name: Save commit hash in version module
      copy:
        content: "GIT_REV='{{ git_rev }}'\n"
        dest: "{{ django_dir }}/{{ django_project }}/version.py"
        mode: 0644
      when: git_rev is defined
    - name: Copy .env file in Django directory
      template:
        src: "{{ django_env_template_path }}"
        dest: "{{ django_dir }}/.env"
      when: django_env_template_path is defined
    - name: Create Python requirements archive
      archive:
        path: "{{ python_requirements_path }}"
        dest: "{{ requirements_archive_path }}"
      delegate_to: localhost
    - name: Create Python requirements dir on the remote server
      file: path={{ requirements_dir }} state=directory mode=0755
    - name: Copy Python requirements to the remote server
      unarchive:
        src: "{{ requirements_archive_path }}/"
        dest: "{{ requirements_dir }}"
    - name: Install python requirements
      pip:
        requirements: "{{ requirements_dir }}/{{ deploy_environment }}.txt"
        extra_args: --upgrade
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_python: python3
      notify:
        - restart uwsgi
- name: Django commands
  tags: django
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_project }}.settings.{{ deploy_environment }}"
  block:
    - name: Execute django collectstatic
      django_manage:
        command: collectstatic
        project_path: "{{ django_dir }}"
        virtualenv: "{{ virtualenv_path }}"
    - name: Execute django migrate
      django_manage:
        command: migrate
        project_path: "{{ django_dir }}"
        virtualenv: "{{ virtualenv_path }}"
    - name: Execute django loaddata
      django_manage:
        command: loaddata
        fixtures: "{{ django_fixtures }}"
        project_path: "{{ django_dir }}"
        virtualenv: "{{ virtualenv_path }}"
      when: django_fixtures is defined
