---
- name: Copy supervisord config file
  become: True
  template:
    src: "{{ role_path }}/templates/supervisord.conf.j2"
    dest: "/etc/supervisor/conf.d/{{ server_name }}.conf"
  notify:
    - restart supervisord
  when: nuxt_supervisord is defined and nuxt_supervisord
