---
- name: Nuxt update sources and requirements
  tags: nuxt
  vars:
    nuxt_build_archive_path: /tmp/nuxt-build.tar.gz
  block:
    - name: Sync Nuxt build on remote
      synchronize:
        src: "{{ nuxt_src_path }}"
        dest: "{{ nuxt_dir }}"
        delete: true
      notify:
        - restart supervisord
    - name: Install Node requirements with yarn
      yarn:
        path: "{{ nuxt_dir }}"
        production: yes
      notify:
        - restart supervisord
    - name: Copy .env file in Nuxt directory
      template:
        src: "{{ nuxt_env_template_path }}"
        dest: "{{ nuxt_dir }}/.env"
      when: nuxt_env_template_path is defined
