---
- name: Add YARN official apt repository pubkey
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
- name: Add YARN official apt repository
  become: True
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
- name: Installing required packages
  become: True
  apt:
    pkg:
      - supervisor
      - yarn
    state: present
