---
# handlers file for nuxt-supervisord
- name: restart supervisord
  become: True
  supervisorctl:
    name: "{{ server_name }}"
    state: restarted
  when: nuxt_supervisord is defined and nuxt_supervisord
